Added device IP discovery
leikoilja/glocaltokens pull request #13
Opened 2021-02-10 21:51 UTC by ArnyminerZ

Through `pychromecast`, the IP is obtained. It's required to enter a list of accepted device model names, but I've already prepared one with the idea to add new devices, and maybe new lists, who knows, it's called `GOOGLE_HOME_MODELS`, since it contains the model names for the Google Home devices I've been able to test.

Example code:
```python
import json
from glocaltokens.client import GLocalAuthenticationTokens
from glocaltokens.scanner import ( discover_devices, GOOGLE_HOME_MODELS, )

client = GLocalAuthenticationTokens(master_token="aas_et/***")

google_devices = client.get_google_devices_json(GOOGLE_HOME_MODELS)
google_devices_str = json.dumps(google_devices, indent=2)

print('[*] Google devices', google_devices_str)
```

2021-02-10 22:05 UTC, ArnyminerZ commented
The detection of IPs makes the load a bit slower, to I've made it optional.

2021-02-10 22:45 UTC, ArnyminerZ commented
Removed `pychromecast` dependency by moving the required code into `scanner.py`. Note that the code has been minified to match needs.

2021-02-11 05:50 UTC, leikoilja commented on glocaltokens/client.py
> +    @staticmethod
Great adding!

2021-02-11 06:06 UTC, DurgNomis-drol commented
This looks great! I will test later too day when I get back from work

2021-02-11 06:15 UTC, leikoilja requested changes
Awesome stuff, thanks a lot! 

There are just a few tiny comments I have. But also, now that we are expanding the package, I really feel like we need to start testing the code more (by unittests). 
Do you mind waiting for a bit for me to set up the testing environment on a `master`, so we could add the a few relevant unit tests here before we merge?

2021-02-11 06:15 UTC, leikoilja commented on glocaltokens/client.py
> +                        continue
Why do we continue if the item's model is not in the supported model list? What should happen if it is?

How about we make `models_list` default to an empty list and here just say 
`if item.hardware.model not in models_list`?

2021-02-11 06:15 UTC, leikoilja commented on glocaltokens/client.py
> +                    if google_device is not None:
Let's just say `if google_device:`

2021-02-11 06:15 UTC, leikoilja commented on glocaltokens/client.py
> +                    google_device = find_device(item.device_name, network_items) if network_items is not None else None
Maybe 
`google_device = find_device(item.device_name, network_items) if network_items else None`
is a bit cleaner?

2021-02-11 06:15 UTC, leikoilja commented on glocaltokens/client.py
> +                        device['port'] = google_device.port
Since device is a dictrionary how about we just update it with:
```python
device.update({
    'ip': google_device.ip,
    'port': google_device.port
})
```
I know there is literally no difference, but it might be helpful if we choose to expand `device` dictionary with more and more parameters as we go

2021-02-11 06:15 UTC, leikoilja commented on glocaltokens/client.py
> +        network_devices = discover_devices(models_list) if models_list is not None else None
Maybe `network_devices = discover_devices(models_list) if models_list else None` ?

2021-02-11 06:15 UTC, leikoilja commented on glocaltokens/scanner.py
> +        _LOGGER.debug("update_service %s, %s", typ, name)
I like that they use logging. We should probs do it too throughout the code

2021-02-11 09:06 UTC, ArnyminerZ commented on glocaltokens/client.py
> +    def get_google_devices_json(self, models_list: Optional[List[str]] = None):
I don't mind using the other notation, but using PyCharm is quite useful to have the "class type", so it can get the object properties, and detect misusages.

2021-02-11 09:07 UTC, ArnyminerZ commented on glocaltokens/client.py
>              """
Removed that, sending new commit, but isn't that function a bit redundant? I believe it had an old usage, but now is kind of out of place, isn't it?

2021-02-11 09:11 UTC, ArnyminerZ commented on glocaltokens/client.py
> +                        continue
The `continue` instruction is a kind of return for loops, it just makes the new loop start, without executing the code that continues, only for this time, I don't know if I'm explaining myself, so I attach a [better explanation](https://www.tutorialspoint.com/python/python_continue_statement.htm).

In this case, it's used to omit the elements in `items` that doesn't have one of the models at `models_list`, so only will get loaded into `devices_result` the ones that match the `models_list` criteria. Should be pointless, but got some chromecasts into those lists, something that shouldn't happen, since we are searching for Google Homes.

2021-02-11 09:11 UTC, ArnyminerZ commented on glocaltokens/client.py
> +                        continue
> How about we make `models_list` default to an empty list and here just say
> `if item.hardware.model not in models_list`?

And yes, that makes more sense, changing that.

2021-02-11 09:17 UTC, ArnyminerZ commented on glocaltokens/client.py
>              """
Removed the docstring in ce7b8d2

2021-02-11 09:17 UTC, ArnyminerZ commented on glocaltokens/client.py
> +                        continue
Improved `models_list` checking in fcf0100 and 5eb4178.

2021-02-11 09:20 UTC, ArnyminerZ commented on glocaltokens/client.py
> +                    if google_device is not None:
See b8a535c

2021-02-11 09:21 UTC, ArnyminerZ commented on glocaltokens/client.py
> +                    google_device = find_device(item.device_name, network_items) if network_items is not None else None
Fixed in b8a535c.

2021-02-11 09:22 UTC, ArnyminerZ commented on glocaltokens/client.py
> +                        device['port'] = google_device.port
See 416893d

2021-02-11 09:23 UTC, ArnyminerZ commented on glocaltokens/scanner.py
> +        _LOGGER.debug("update_service %s, %s", typ, name)
Yes, that should really be there, maybe a new issue for more debugging?

2021-02-11 09:24 UTC, ArnyminerZ commented on glocaltokens/client.py
> +        network_devices = discover_devices(models_list) if models_list is not None else None
Made a kind of different approach 5eb4178

2021-02-11 09:25 UTC, ArnyminerZ commented on glocaltokens/client.py
> +    @staticmethod
😉 it might be convenient in other places too, will take a look.

2021-02-11 09:26 UTC, ArnyminerZ commented
> Do you mind waiting for a bit for me to set up the testing environment on a `master`, so we could add the a few relevant unit tests here before we merge?

Yes, of course, I don't mind waiting, testing is a must-have. Sorry that I don't have much experience and can't help working on it, but will wait paciently.

2021-02-11 13:02 UTC, leikoilja commented on glocaltokens/client.py
> +    def get_google_devices_json(self, models_list: Optional[List[str]] = None):
I can see that's being super useful when the editor is set right. I m using `vim` and currently don't have any linters helping me this python types. might need to set it up later. It reminds me of type-script concepts with typing. 
Shall we remove it for now and have a separate tracking issue where we refactor the codebase to use the typing around the entire package?

2021-02-11 13:06 UTC, leikoilja commented on glocaltokens/scanner.py
> +        _LOGGER.debug("update_service %s, %s", typ, name)
Sounds good with me! Do you mind creating it? Just reference this conversation or smth. Thanks

2021-02-11 13:20 UTC, leikoilja requested changes
Great job 😎 
Let's remove typing for now and introduce it across the entire project as a new next feature (could you please create a separate issue for that, so we could track it?).

I will try finding time tonight to setup test environment so we could crunch up some unittests for this one! 
Thanks!

2021-02-11 13:20 UTC, leikoilja commented on glocaltokens/client.py
> +            models_list = []
I'm just being picky 😄  
We can have it as a sexy one-liner:
`models_list = models_list if models_list else []`

2021-02-11 13:20 UTC, leikoilja commented on glocaltokens/client.py
> +        def find_device(name, devices_list) -> Optional[GoogleDevice]:
Let's remove typing for now. Please see https://github.com/leikoilja/glocaltokens/pull/13/files#r574483411

2021-02-11 13:20 UTC, leikoilja commented on glocaltokens/client.py
> +                    if len(models_list) > 0 and item.hardware.model not in models_list:
Just to make it simplier, I believe python will return false for an empty list. 
So you can just say `if models_list and ....` just to make it a bit cleaner, but it's up to you

2021-02-11 13:20 UTC, leikoilja commented on glocaltokens/client.py
> +        network_devices = discover_devices(models_list) if len(models_list) > 0 else []
You could also omit `len(...)>0` here, same as in the previous case.

2021-02-11 14:16 UTC, ArnyminerZ commented
Ok, will create separate issue for typing, and will start migrating ASAP :wink:

2021-02-11 17:45 UTC, leikoilja commented
@ArnyminerZ, I have just pushed a bare-bone setup for testing environment which would be up and running on master now 😄 
Please check README's Contribution section where I put some words about testing. I have also tried writing a few simple unittests that we can use when adding more tests. 
It would be great if you could rebase your branch to the `master` and then add a few tests for the new functionality. Please take a look at my comments above as well. 
Thanks a lot 💥

2021-02-12 08:03 UTC, leikoilja commented
@ArnyminerZ, have you seen this one https://developers.home-assistant.io/docs/creating_integration_manifest/#zeroconf? 
I m wondering if this could work for us, but i doubt it a little. If i understand it correctly if we would to use HA zeroconf then we should delegate autodiscovery to `HA-glocaltokens` project. And then it might be hard to map tokens with those devices, am i right? The reason why we want to keep it in `glocaltokens` is to discover devices and map them with tokens, right?

2021-02-12 09:15 UTC, ArnyminerZ commented
> @ArnyminerZ, have you seen this one https://developers.home-assistant.io/docs/creating_integration_manifest/#zeroconf? 
> I m wondering if this could work for us, but i doubt it a little. If i understand it correctly if we would to use HA zeroconf then we should delegate autodiscovery to `HA-glocaltokens` project. And then it might be hard to map tokens with those devices, am i right? The reason why we want to keep it in `glocaltokens` is to discover devices and map them with tokens, right?

In fact, that should totally work. Will take a look this afternoon, since I have been a bit busy for exams those days.

2021-02-12 09:45 UTC, ArnyminerZ commented on glocaltokens/client.py
> +                    if len(models_list) > 0 and item.hardware.model not in models_list:
Fixed it 60f9c86

2021-02-12 09:45 UTC, ArnyminerZ commented on glocaltokens/client.py
> +        network_devices = discover_devices(models_list) if len(models_list) > 0 else []
Fixed it 60f9c86

2021-02-12 09:48 UTC, ArnyminerZ commented on glocaltokens/client.py
> +        def find_device(name, devices_list) -> Optional[GoogleDevice]:
Removed typing bf25bd5

2021-02-12 09:50 UTC, ArnyminerZ commented on glocaltokens/client.py
> +            models_list = []
Gotcha f7ceea3

2021-02-12 09:51 UTC, ArnyminerZ commented on glocaltokens/scanner.py
> +        _LOGGER.debug("update_service %s, %s", typ, name)
Done it #16

2021-02-12 09:54 UTC, ArnyminerZ commented on glocaltokens/client.py
> +    def get_google_devices_json(self, models_list: Optional[List[str]] = None):
Removed typing at bf25bd5 added a suggestion at #17

2021-02-12 09:55 UTC, ArnyminerZ reviewed
Fixed all requests. Testing still missing

2021-02-12 09:57 UTC, ArnyminerZ reviewed
Fixed everything for now

2021-02-13 10:08 UTC, leikoilja commented
Thank you, @ArnyminerZ. How is it going with testings, do you need any help? 💥 🤓 
Also, please see https://github.com/leikoilja/glocaltokens/pull/19, I have enhanced logging and enabled pre-commit hooks so that all the code is linted to Black. You might want to rebase this branch to the latest `master`.

2021-02-13 10:23 UTC, ArnyminerZ commented
> Thank you, @ArnyminerZ. Hope your exams are going well.
I finished them yesterday,so I will be full-time with this 😈

> How is it going with testings, do you need any help? 💥 🤓
I'm researching a little bit, since I've never used testing before, so I'm a bit lost.

> Also, please see #19, I have enhanced logging and enabled pre-commit hooks so that all the code is linted to Black. You will need to rebase this branch to the latest `master` to avoid merge conflicts. Let me know if you need any assistance with that 🤝
#19 looks awesome, great job ✨. I might add some more logging to scanner. I will try to rebase the `master` branch rn, but it's my first time working with git this hardly, so I'm a bit noob, don't blame me xD. Learning everyday 😋

2021-02-13 10:28 UTC, leikoilja commented
haha, no worries at all, @ArnyminerZ.

I have done a bit of testing and know a thing or two about rebasing/merge conflicts etc, so feel free to ask questions if I may be of any use 😉  💥

2021-02-13 11:45 UTC, ArnyminerZ commented
@leikoilja I was trying to push my changes after having merged everything correctly, and added tests for `scanner.py`, but I'm getting the following error:
```
error: failed to push some refs to 'https://github.com/ArnyminerZ/glocaltokens.git'
To https://github.com/ArnyminerZ/glocaltokens.git
!	refs/heads/device-discovery:refs/heads/device-discovery	[remote rejected] (refusing to allow an OAuth App to create or update workflow `.github/workflows/tests.yaml` without `workflow` scope)
Done
```

Any ideas of what am I doing wrong? Thanks

2021-02-13 11:51 UTC, leikoilja commented
@ArnyminerZ, yeh, that's some of the settings I have tried on the repo to only allow merges after the tests have passed. Just removed it, the guy again 💥

2021-02-13 11:54 UTC, ArnyminerZ commented
> 
> 
> @ArnyminerZ, yeh, that's some of the settings I have tried on the repo to only allow merges after the tests have passed. Just removed it, the guy again 💥

I think that was my fault, I was using Git from PyCharm, and my Github Token didn't have the `workflow` scope enabled.

2021-02-13 11:56 UTC, ArnyminerZ commented
I believe I should have added the commits to this PR, but can you confirm? I can't see them. It's from f7ceea3 to forward.

2021-02-13 12:09 UTC, ArnyminerZ reviewed
Completed all suggestions

2021-02-14 15:54 UTC, DurgNomis-drol commented
Be sure that the port you return from auto discovery is 8443 as prescribed in ha-glocaltokens. This is port that all request should made to on the local google home device.

2021-02-15 06:39 UTC, leikoilja requested changes
Awesome job, we are ready to merge it in, wohooo!! 🚀  
The network tests are superb! 💣 
Just a few small last comments, hope they are relevant 💥  Please 're-request' review when done, so i can jump in and we can merge it.
Thanks man 💯

2021-02-15 06:39 UTC, leikoilja commented on glocaltokens/client.py
> +                            'port': google_device.port
As @DurgNomis-drol has suggested we could do a port validation to ensure it is `8443` here, before adding, but I think it's should not be a job for `glocaltokens` to begin with. I suggest we keep it simple here since this client can be used for multiple various applications. I suggest we add port validation in `ha-glocaltokens` repo if we find it's needed :)

2021-02-15 06:39 UTC, leikoilja commented on glocaltokens/client.py
> +    def get_google_devices_json(self, models_list: Optional[List[str]] = None, indent: int = 2):
Can you please remove the remainings of typing here as well? :)

2021-02-15 06:39 UTC, leikoilja commented on glocaltokens/scanner.py
> +]
Can we please add a few words to the README to inform the user that currently, we support these Google Home models. 
Otherwise, some of Google Home device discovery can silently fail. For example, I have Google Nest Audio at home which will probably not be discovered as of now :)

2021-02-15 06:39 UTC, leikoilja commented on glocaltokens/scanner.py
> +        if not net_utils.is_valid_ipv4_address(ip) and not net_utils.is_valid_ipv4_address(ip):
Did you mean to do the check twice? I suspect you wanted to check for ipv4 and ipv6, right?

2021-02-15 06:39 UTC, leikoilja commented on glocaltokens/scanner.py
> +        self.port = int(port)
Why do we check if `port` is an integer and only continue if the check passes. And then we still typecast it to `int`? Is it just for an added protection?

2021-02-15 06:39 UTC, leikoilja commented on glocaltokens/scanner.py
> +            return
That's great, but we could also just check if it's in a range between [0; 65535] and then display one error message if otherwise. Up to you 💥

2021-02-15 06:39 UTC, leikoilja commented on tests/test_scanner.py
> +faker.add_provider(python_provider)
Awesome use of providers!

2021-02-15 10:18 UTC, ArnyminerZ commented on glocaltokens/scanner.py
> +            return
Yeah, much neater, added it in 96a202c

2021-02-15 10:18 UTC, ArnyminerZ commented on tests/test_scanner.py
> +faker.add_provider(python_provider)
😸

2021-02-15 11:12 UTC, leikoilja commented on glocaltokens/scanner.py
> +        if not net_utils.is_valid_ipv4_address(ip) and not net_utils.is_valid_ipv4_address(ip):
@ArnyminerZ can you please fix this one before we merge? :)

2021-02-15 11:39 UTC, ArnyminerZ commented on glocaltokens/client.py
> +                            'port': google_device.port
I wasn't adding the check because maybe this library could be used for other devices, and not just Google Homes, so as you have said, this port check should be done by `ha-glocaltokens`.

2021-02-15 11:41 UTC, ArnyminerZ commented on glocaltokens/scanner.py
> +]
Yeah, will add this, it's quite important. Also, this is kind of a pre-defined const, you could create your own models list. Anyway, I'm adding it to README so it's clear.

2021-02-15 11:47 UTC, ArnyminerZ commented on glocaltokens/scanner.py
> +]
Added in ca9dd2d

2021-02-15 11:50 UTC, ArnyminerZ commented on glocaltokens/scanner.py
> +        self.port = int(port)
Just realized about that, added the `int(port)` before the previous check, which was added during the tests addition. I believe it's a bit redundant, so will remove.

2021-02-15 11:51 UTC, ArnyminerZ commented on glocaltokens/scanner.py
> +        if not net_utils.is_valid_ipv4_address(ip) and not net_utils.is_valid_ipv4_address(ip):
Yeah, that was a IPv4 and IPv6 check, just a copy-paste typo

2021-02-15 11:52 UTC, ArnyminerZ commented on glocaltokens/client.py
> +    def get_google_devices_json(self, models_list: Optional[List[str]] = None, indent: int = 2):
Fixed cafe4bf

2021-02-15 11:53 UTC, ArnyminerZ commented on glocaltokens/scanner.py
> +        self.port = int(port)
Fixed 84735b6

2021-02-15 11:53 UTC, ArnyminerZ commented on glocaltokens/scanner.py
> +        if not net_utils.is_valid_ipv4_address(ip) and not net_utils.is_valid_ipv4_address(ip):
Fixed 1e0ceb1

2021-02-15 11:53 UTC, leikoilja commented on README.md
> +- Lenovo Smart Cloc
@ArnyminerZ tiny typo

2021-02-15 11:54 UTC, ArnyminerZ reviewed
Reviewed changes

2021-02-15 11:56 UTC, ArnyminerZ commented on README.md
> +- Lenovo Smart Cloc
OMG 🤦🏼 fixed c2d6666

2021-02-15 11:56 UTC, ArnyminerZ reviewed
Fixed typo

2021-02-15 11:59 UTC, ArnyminerZ reviewed
Everything should be fine now

2021-02-15 11:59 UTC, leikoilja approved these changes
Uhhh, awesome work, man 💥  I'm happy we got to merge it! I ll try testing it tonight as well to make sure it doesn't break anything and IP discovery works. Unfortunately don't have RPi at hands to give it a proper run, so I hope I won't miss anything.

2021-02-15 12:00 UTC, leikoilja commented
@ArnyminerZ  let's try doing smaller PRs if possible in the future, that way we can break down some work into smaller chunks and it will be easier to review 😄  Thanks tons!

2021-02-15 12:00 UTC, ArnyminerZ commented
> Unfortunately don't have RPi at hands to give it a proper run, so I hope I won't miss anything.

If you need to make any test, tell me through here, for example, and I can test in a RPi both in Alpine and Ubuntu

2021-02-15 12:00 UTC, merged

2021-02-15 12:01 UTC, ArnyminerZ commented
> 
> 
> @ArnyminerZ let's try doing smaller PRs if possible in the future, that way we can break down some work into smaller chunks and it will be easier to review 😄 Thanks tons!

Yeah, it's been quite a mess, I'm still a bit dumb around Github, will get better and better 🦾.

2021-02-15 12:02 UTC, leikoilja commented
haha, you are doing great, @ArnyminerZ 🏅 🚀