Add possibility of using an address list instead
leikoilja/glocaltokens pull request #202
Opened 2021-12-01 16:08 UTC by DurgNomis-drol

This changes `disable_discovery` from a bool to `address_list` containing a dict. Example dict: ``{"Living room": "192.168.0.69"}` Not setting the address_list results in discovery been enabled. Setting it to and empty dict results in discovery being disabled.

I was not 100% sure on how to best implement this, so please provide feedback if something can be done better. 😄 

Code is tested, but can someone double check to make sure that we are not breaking anything with this.

2021-12-01 16:12 UTC, DurgNomis-drol commented
I am unsure of why the linter fails to install poetry

2021-12-02 07:42 UTC, leikoilja requested changes
That's an amazing improvements, thanks man! Have a few suggestions

2021-12-02 07:42 UTC, leikoilja commented on glocaltokens/client.py
> +        address_list: Dict[str, str] | None = None,
What do you think about naming it `discovery_address_list`?

2021-12-02 07:42 UTC, leikoilja commented on glocaltokens/client.py
>              LOGGER.debug("Getting network devices...")
Can we please adjust the log message here? 
```suggestion
        if address_list is None:
            LOGGER.debug("Automatically discovering network devices...")
```

2021-12-02 07:42 UTC, leikoilja commented on glocaltokens/client.py
>            be searched for in the network.
```suggestion
        address_list: Dict of network devices from the local network ({"name": "ip_address"}). If set to `None` will try to automatically discover network devices. Disable discovery by setting to `{}`
```

2021-12-02 07:42 UTC, leikoilja commented on glocaltokens/client.py
>            be searched for in the network.
Also it's not really a `list` per say. Maybe we can call it `discovery_addresses` to avoid confusion of `list -> []`

2021-12-02 07:42 UTC, leikoilja commented on glocaltokens/client.py
> +                else:
I suggest instead of `else` we do smth like:
```python
elif item.device_name in address_list:
  network_device = NetworkDevice(
                        name=item.device_name,
                        ip_address=address_list[item.device_name],
                        port=0,
                        model=item.hardware.model,
                        unique_id=item.device_info.device_id,
                    )
```
But i m a bit unsure why do we set post to `0`? Can you please check what port is here for auto discovered network items? It's probably some sort of specific discovery port. If so, we need to add it to `const` and use as static

2021-12-02 07:42 UTC, leikoilja commented on glocaltokens/client.py
> +                    else man_disc_device,
We can have it a bit cleaner if we choose to go with `elif` as suggested above
```suggestion
                    network_device=network_device,
```

2021-12-02 07:42 UTC, leikoilja commented on tests/factory/providers.py
> +            device_name = faker.word()
```suggestion
            device_name = device_name if device_name else faker.word()
```

2021-12-02 07:42 UTC, leikoilja commented on tests/test_client.py
>          self.assertEqual(len(google_devices), 1)
It would be nice to fake generate ip address using `faker` here and then assert that `google_device` has the name same as `fake_device_name` and ip is the same as you fake generated ip

2021-12-02 17:20 UTC, DurgNomis-drol commented on glocaltokens/client.py
> +                else:
We discover the port through Zeroconf. The reason I set it to `0` is because i didn't want to mess with `NetworkDevice` and change the typing for port to `int | None` instead of just `int`. Should i just make a `const` with that standard port it returns or is it better that we return something like `None` or `0` to signal that the port was not discovered?

2021-12-02 17:22 UTC, DurgNomis-drol commented on glocaltokens/client.py
> +        address_list: Dict[str, str] | None = None,
Fine with me, i struggled to find a good name 😃

2021-12-02 17:26 UTC, DurgNomis-drol commented on glocaltokens/client.py
>            be searched for in the network.
You are right, what about `discovery_address_dict`?

2021-12-02 18:22 UTC, DurgNomis-drol commented on glocaltokens/client.py
> +        address_list: Dict[str, str] | None = None,
See below, have named it `discovery_address_dict`

2021-12-02 18:23 UTC, DurgNomis-drol commented on glocaltokens/client.py
> +                else:
Partly resolved this, need you input about the port thing 😄

2021-12-02 18:24 UTC, DurgNomis-drol commented on glocaltokens/client.py
>            be searched for in the network.
Changed it to `discovery_address_dict`

2021-12-02 18:26 UTC, DurgNomis-drol commented
Please see my changes and the last comment that are open 😃

2021-12-03 06:45 UTC, leikoilja approved these changes
Yay! Amazing job, man! Thanks 💯 
Just a minor comment about default IPs/port and it's good to go 🚀

2021-12-03 06:45 UTC, leikoilja commented on glocaltokens/client.py
> +                        or "0.0.0.0",
I still believe we should not default the IP to 0.0.0.0.
According to wikipedia

> the address 0.0. 0.0 is a non-routable meta-address used to designate an invalid, unknown or non-applicable target

We are getting `discovery_address_dict` from the user so it must contain name and IP of devices, right? If you want to make it extra rigid we can add an inout validation to the `get_google_devices` function to check the data in `discovery_address_dict` to contain expected name/ip pairs, so if the input `dict` is invalid we raise the error :)

```suggestion
                        ip_address=discovery_address_dict[item.device_name],
```

2021-12-03 06:45 UTC, leikoilja commented on glocaltokens/client.py
> +                        port=0,
hmm, i m not so sure what to do with this port. Perhaps you are right and we should not assign autodiscovery port if the device was matched by manual entry. Shall we maybe default to port `80` then, which is the default access port? :) But either way, let's make it a static and move to `const` file

2021-12-03 06:45 UTC, leikoilja commented on tests/test_client.py
> +            self.assertEqual(google_device.network_device.ip_address, fake_ip_address)
Flip yeh, let's make those tests robust! 💪

2021-12-03 13:39 UTC, DurgNomis-drol commented on glocaltokens/client.py
> +                        or "0.0.0.0",
I think it is a great idea to validate the input

2021-12-03 13:40 UTC, DurgNomis-drol commented on glocaltokens/client.py
> +                        port=0,
I will move it to a const, don't think it is a good idea to set it to port 80 though.

2021-12-03 14:32 UTC, DurgNomis-drol commented on glocaltokens/client.py
> +                        or "0.0.0.0",
I have added input validation to the dict, it also checks if the IP address is a valid IPv4 address 😄

2021-12-03 15:11 UTC, DurgNomis-drol commented
I have no idea of what went wrong and why it essentially deletes and the adds `client.py` when the new lines again, but i don't have time to fixed it today, will fixed it tomorrow

2021-12-03 15:12 UTC, DurgNomis-drol commented
Can it be line endings?

2021-12-04 15:49 UTC, DurgNomis-drol commented
Got it fixed, i have no idea what went wrong but rolled back to a working commit and fixed the linter.

@leikoilja Can I get you to release a new version after this is merged? :smiley:

2021-12-04 17:27 UTC, KapJI commented on poetry.lock
> -version = "20.3.0"
Looks like you accidentally ran `poetry upgrade`, please revert this file. If you want to upgrade dependencies, create a separate PR.

2021-12-04 17:31 UTC, DurgNomis-drol commented on poetry.lock
> -version = "20.3.0"
Will revert it, but i didn't run `poetry upgrade`.

2021-12-04 17:41 UTC, KapJI commented
Can you give some context about what problem you're solving with this?

2021-12-04 17:44 UTC, DurgNomis-drol commented on poetry.lock
> -version = "20.3.0"
Can it be that i ran `poetry update` on this branch?

2021-12-04 17:49 UTC, DurgNomis-drol commented
> Can you give some context about what problem you're solving with this?

https://github.com/leikoilja/ha-google-home/issues/340 is just one of them.

As i am working on moving the ha-google-home code to the separate module, i ran into some problems with zeroconf on WSL2. Code run in WSL2 can't discover devices through zeroconf. This just makes it much easier for me to test it when i am developing.

2021-12-04 17:50 UTC, DurgNomis-drol commented on poetry.lock
> -version = "20.3.0"
Should be fixed now

2021-12-04 18:16 UTC, KapJI commented
Thanks, makes sense.

I think breaking compatibility for such change is not necessary, so let's keep `disable_discovery`.

Instead add `extra_addresses` argument in the end. IP address should be the key. And append it to list of discovered devices.

2021-12-04 18:26 UTC, DurgNomis-drol commented
@KapJI No. We need to pass the name of the device as the key and the IP address as the value. If we don't, we can't match the IP address to the device and so on.

Making it a separate argument, means the user now needs to set `disable_discovery` to `true` and then set a dict with addresses. Using my way, we just disable it automatically if we have dict containing addresses.

2021-12-04 18:29 UTC, KapJI commented
You don't need to disable discovery completely. If it crashes on WSL2, you can disable it automatically if running inside WSL2.

Mapping from IP to name makes more sense from UX perspective which I believe should come before implementation. You can build reverse dict here if needed.

2021-12-04 18:35 UTC, DurgNomis-drol commented
I Think you are missing the point of what i am trying to do with this PR.

It dosen't make sense to reverse it like you are takling about. We match on device name not the IP.

2021-12-04 18:42 UTC, KapJI commented
Ok, having name as a key is fine actually.

2021-12-04 19:18 UTC, leikoilja commented
Nice!
Awesome thing we have more opinions and reviewers in here. I am not particularly worried about breaking compatibility, since we don't rely on that in `ha-google-home` and we can't really know if there is anyone using `disable_discovery` kwarg at all, so IMHO it shouldn't be a biggie. I ll leave it up to you, @DurgNomis-drol, to decide whether or not you want to refactor it into a separate kwarg keeping `disable_discovery`, but feel free to merge when you ready! 🚀 
p.s. also given you the full repo permissions in the repo, not sure why it wasn't set in the first place 💯 
Thanks man! 🔥

2021-12-04 19:42 UTC, DurgNomis-drol commented
@leikoilja Thanks for both invites! Haven really been active here, so that is fine that i am only getting it now :laughing: 

I will let @KapJI suggestions about `disable_discovery` tumble around in my head until tomorrow, just to make sure i am not missing something :smile: Right now i can't see the use for a separate argument

2021-12-05 09:23 UTC, KapJI commented
Aoproach I proposes should be more flexible. Basically you can still use discovery and extend it with your own list. Also empty dict for disabling discovery while None enables it, is not very clear API.

2021-12-06 14:28 UTC, DurgNomis-drol commented
@KapJI Good point about it not being clear the way i have proposed.

2021-12-06 16:03 UTC, leikoilja commented on glocaltokens/client.py
> +            # Test if the data structure is correct and if each entry contains a
```suggestion
            # Validate the data structure is correct and that each entry contains a
```

2021-12-06 16:05 UTC, leikoilja commented on glocaltokens/client.py
> +                "Invalid dictionary structure for discovery_address_dict "
```suggestion
                "Invalid dictionary structure for addresses dictionary "
```

2021-12-06 16:05 UTC, leikoilja commented on glocaltokens/client.py
> +        if addresses and not is_dict_with_valid_ipv4_addresses(addresses):
Tbh i don't know if there is any benefit of the proposed approach but it looks more readable, isn't it? Or is it just me? :D 

```suggestion
        if addresses and is_dict_with_valid_ipv4_addresses(addresses) is False:
```

2021-12-06 16:07 UTC, leikoilja commented on glocaltokens/client.py
> +        address_dict = addresses if addresses else {}
This could probably just be `addresses = addresses if addresses else {}`, no need for a new variable?

2021-12-06 19:03 UTC, DurgNomis-drol commented on glocaltokens/client.py
> +        if addresses and not is_dict_with_valid_ipv4_addresses(addresses):
Your way is more readable, but the other way is the pythonic way to do it, as far as i know

2021-12-06 19:06 UTC, DurgNomis-drol commented on glocaltokens/client.py
> +        address_dict = addresses if addresses else {}
mypy will throw a typing error, because `addresses` is optional `dict`, and when we access it below when setting a `network_devices` we get a typing error expecting `str`, got optional `str`.

2021-12-07 09:32 UTC, leikoilja commented on glocaltokens/client.py
> +        if addresses and not is_dict_with_valid_ipv4_addresses(addresses):
haha same :D

2021-12-07 09:32 UTC, leikoilja commented on glocaltokens/client.py
> +        address_dict = addresses if addresses else {}
nice to know, thanks 👍

2021-12-07 09:33 UTC, leikoilja commented
Amazing work, thank you, @DurgNomis-drol 💯 🔥

2021-12-07 09:33 UTC, merged

2021-12-07 09:45 UTC, leikoilja commented
ping @DurgNomis-drol for v0.6 release

2021-12-07 10:56 UTC, KapJI commented on glocaltokens/client.py
> +                elif item.device_name in address_dict:
This means if discovery is enabled, `address_dict` won't be used. That contradicts the idea to have separate `disable_discovery` flag.

2021-12-07 10:57 UTC, KapJI commented on glocaltokens/client.py
> +                        ip_address=address_dict[item.device_name],
Case when there is no item with such name is not handled which will cause whole integration to crash.

2021-12-07 11:00 UTC, KapJI commented on glocaltokens/client.py
> +                elif item.device_name in address_dict:
Also if there's no item with such name in `address_dict`, it's worth to print a warning message.

2021-12-07 11:03 UTC, KapJI commented on glocaltokens/client.py
> +        addresses: dict[str, str] | None = None,
It's better to add new arguments in the end, to not break reverse compatibility.