Implement typing
leikoilja/glocaltokens pull request #22
Opened 2021-02-15 10:04 UTC by ArnyminerZ

I've implemented typing on I believe all the functions. I've also added some tests for token format checking, and variable type checks.

2021-02-15 11:17 UTC, leikoilja reviewed
Looks really good, thanks for implementing it! 💥 

Let's wait to merge the https://github.com/leikoilja/glocaltokens/pull/13 then rebase to latest `master` on this repo and then the only changes left here will be from implementing typing and type checks. It will be easier to review and I ll do it right away, so we can get it merged 👍

2021-02-15 12:02 UTC, leikoilja commented
Now that the #13 is merged, we have got some conflicts here. Can you please rebase it to the latest `master` and force push your changes into this branch? then i'll be able to review it easier 😄

2021-02-15 12:06 UTC, ArnyminerZ commented
I believe all the conflicts should be fixed

2021-02-15 12:32 UTC, leikoilja requested changes
Awesome stuff! Just a few small comments

2021-02-15 12:32 UTC, leikoilja commented on glocaltokens/client.py
> +        if self.ip and not net_utils.is_valid_ipv4_address(self.ip) and not net_utils.is_valid_ipv4_address(self.ip):
The typo here again with ipv4 and ipb6

2021-02-15 12:32 UTC, leikoilja commented on glocaltokens/client.py
> +    def dict(self) -> []:
isn't the return type here `Dict`?

2021-02-15 12:32 UTC, leikoilja commented on glocaltokens/client.py
> +        return json.dumps(devices_json, indent=indent)
Would be great to add a Client test for that one. This method must be quite robust, so it's important we have it covered with tests. Will create a new issue for that

2021-02-15 12:32 UTC, leikoilja commented on glocaltokens/scanner.py
> +        if not net_utils.is_valid_ipv4_address(ip) and not net_utils.is_valid_ipv4_address(ip):
Why do you change it to ipv4 here?

2021-02-15 12:32 UTC, leikoilja commented on tests/factory/providers.py
> +        return "aas_et/" + "".join(random.choice(string.ascii_letters) for x in range(216))
Let's reuse the method from `glocaltokens/utils/token.py` here, so we don't duplicate them

2021-02-15 12:32 UTC, leikoilja commented on tests/factory/providers.py
> +        return "".join(random.choice(string.ascii_letters) for x in range(108))
Same here

2021-02-15 12:32 UTC, leikoilja commented on tests/test_client.py
> +        master_token = faker.aas_et()
can we maybe prefix the `aas_et` with `token_aae_et`? It would be more elaborate then and we could introduce easily another token types if needed

2021-02-15 12:32 UTC, leikoilja commented on tests/test_client.py
> +        self.assertTrue(type(client.username) == str)
I suggest we do a separate test mixin for that type of checks. It would look like this:

```python
class TypeTestMixin:
 
  def assertIsString(self, variable):
    self.assertTrue(type(variable) == str, msg=f"Given variable {variable} is not String type")

class GLocalAuthenticationTokensClientTests(TypeTestMixin, TestCase):
   ...
   self.assertIsString(client.master_token)
```

2021-02-16 09:03 UTC, ArnyminerZ commented on glocaltokens/client.py
> +        return json.dumps(devices_json, indent=indent)
Yeah, the issue is that I didn't know how to test it, since it's calling methods that require your Google Account, how to I build tests on that one?

2021-02-16 09:20 UTC, ArnyminerZ commented on glocaltokens/client.py
> +        if self.ip and not net_utils.is_valid_ipv4_address(self.ip) and not net_utils.is_valid_ipv4_address(self.ip):
Fixed 29f19f4

2021-02-16 09:21 UTC, ArnyminerZ commented on glocaltokens/client.py
> +    def dict(self) -> []:
Yeah, I don't know why I put that. Fixed 6155351.

2021-02-16 09:21 UTC, ArnyminerZ commented on glocaltokens/scanner.py
> +        if not net_utils.is_valid_ipv4_address(ip) and not net_utils.is_valid_ipv4_address(ip):
🤔 8732573

2021-02-16 09:22 UTC, ArnyminerZ commented on tests/factory/providers.py
> +        return "aas_et/" + "".join(random.choice(string.ascii_letters) for x in range(216))
Unified in a function which may also be useful in the future. c2d5516

2021-02-16 09:22 UTC, ArnyminerZ commented on tests/factory/providers.py
> +        return "".join(random.choice(string.ascii_letters) for x in range(108))
Check the [other message](https://github.com/leikoilja/glocaltokens/pull/22#discussion_r576667308).

2021-02-16 09:22 UTC, ArnyminerZ commented on tests/test_client.py
> +        master_token = faker.aas_et()
Renamed to `token_aas_et`. 7d7fa1d

2021-02-16 09:23 UTC, ArnyminerZ commented on tests/test_client.py
> +        self.assertTrue(type(client.username) == str)
Added `assertIsString` and `assertIsAASET` in 52ea81d

2021-02-16 09:32 UTC, leikoilja commented on glocaltokens/client.py
> +        return json.dumps(devices_json, indent=indent)
We can use `mock.patch` for this.
You can leave it for me, I can do that after we merge this one (because it will rely on token generation) and then you can take a look of how to do that and maybe learn something new from it :)

2021-02-16 09:34 UTC, leikoilja commented on tests/test_client.py
> +        master_token = faker.aas_et()
@ArnyminerZ it i's great that you are refering to specific commits everytime you fix something, but if it takes too much time you can skip doing that. If the conversation is ongoing just keep it "unresolved" and if you agree with a comment and fixed something you can simply press "resolve conversation". Because when you re-request the review, I will still go through all the files again and see all changes at once :)

2021-02-16 09:38 UTC, leikoilja commented
@ArnyminerZ, we have a new cool `pre-commit` github action that does a lot of code linting and checks so we have the code consistent. You can read more about it here: https://pre-commit.com/

But all in all, what you need to do is install `pip pre-commit` first and then run `pre-commit install` in the working directory. This will install `git` hooks that will be run EVERY time you commit the code. It will happen automatically, but for now just run `pre-commit run --all-files` to manually trigger it and you will see a lot of files being changed and linted :) 
After lining, commit the code and push it here. You will see the `pre-commit` action pass

2021-02-16 10:13 UTC, ArnyminerZ commented on tests/test_client.py
> +        master_token = faker.aas_et()
Ok, I don't mind referencing the issues, it's a matter of seconds, but if it's not useful, I will just mark them as resolved 😉

2021-02-16 10:30 UTC, leikoilja requested changes
Great stuff! Please see a few comments and make sure to run `pre-commit` hooks to lint the code using Black standard.

See my previous comment about `pre-commit`

2021-02-16 10:30 UTC, leikoilja commented on tests/factory/mixin.py
> +                        msg=f"Given variable {variable} doesn't follow the AAS_ET format")
Awesome stuff adding it in a factory directory. It's not really a factory at this point, but that's just details, let's keep it here for now :)

2021-02-16 10:30 UTC, leikoilja commented on tests/factory/providers.py
> +        return generate_token(108)
Awesome stuff

2021-02-16 10:30 UTC, leikoilja commented on tests/test_client.py
> +        client = GLocalAuthenticationTokens(username, password)
You already have a client here, no need to create a new one, just use the existing on

2021-02-16 10:30 UTC, leikoilja commented on tests/test_client.py
> +        self.assertIsString(client.android_id)
You can even move this check into the test we already have `test_get_android_id`

2021-02-16 11:04 UTC, leikoilja approved these changes
Awesome work! Thank you.

Let's see the tests pass and then merge it in! 💥

2021-02-16 11:36 UTC, merged