Adding client tests for fetching tokens
leikoilja/glocaltokens pull request #30
Opened 2021-02-17 19:45 UTC by leikoilja

Haven't really had time to finish it up with `homegraph` and `get_devices`, but added some client tests to make sure we fetch tokens right.

2021-02-17 20:29 UTC, ArnyminerZ requested changes
Awesome work! Great naming changes, and incredible testing 😮

2021-02-17 20:29 UTC, ArnyminerZ commented on glocaltokens/client.py
> +    def _has_expired(creation_dt, duration):
Makes sense. Please, use typing. Maybe `_has_expired(creation_dt: datetime, duration: int) -> bool`? Not sure about that

2021-02-18 06:05 UTC, leikoilja commented on glocaltokens/client.py
> +    def _has_expired(creation_dt, duration):
Oh right, sorry, completely forgot about typing. Pretty new concept for my in python, so thanks for reminding :)

2021-02-18 06:24 UTC, leikoilja commented
Thanks, @ArnyminerZ! 💥  I have just added homegraph test too, which is pretty simple i guess.
Do you want to try taking the `get_devices` and `get_devices_json` methods to test? It could be a fun practise, if you are up for a challenge 💯 No worries if you are busy with something, we have a ticket for it (https://github.com/leikoilja/glocaltokens/issues/23), so I ll just pick it up a bit later

2021-02-18 07:17 UTC, ArnyminerZ commented
Ok, I can try developing them by seeing your work. Will take a try 😉

2021-02-18 07:17 UTC, ArnyminerZ approved these changes

2021-02-18 07:52 UTC, leikoilja commented
@ArnyminerZ sounds amazing! Feel free to make another branch and reference #30 issue there. You can also always push your work into a branch, open a PR and prefix it's title with [WIP] (standing for "work in progress"), then you can ping me or anyone else in the comments in that PR and ask help if needed 💥

2021-02-18 07:52 UTC, merged