Get devices testing
leikoilja/glocaltokens pull request #31
Opened 2021-02-18 09:53 UTC by ArnyminerZ

Added `get_google_devices` and `get_google_devices_json` checks, as well as some optimizations.

2021-02-18 09:55 UTC, ArnyminerZ commented
@leikoilja please, can you take a look at the tests? Not sure what am I doing wrong here.

2021-02-18 10:17 UTC, leikoilja requested changes
Those are some really nice refactoring! 

Uh that's actually a tough tests to make, now that i am thinking about it. 
To fully test it, we will probably need to  patch `homegraph.home.devices` to return a list of objects like homegraph would actually return (just with a fake data). And then validate that we serialize and create `Device` objects correctly from that received payload.
I will try looking at it later tonight to see how can I help with that :) 

We could also create a separate label for `tests` if you feel it might be useful! Feel free to create it, you should have permissions to do so 👍

2021-02-18 10:17 UTC, leikoilja commented on glocaltokens/client.py
> +        disable_discovery: Whether or not the device's IP and port should be searched for in the network.
Great stuff!

2021-02-18 10:17 UTC, leikoilja commented on glocaltokens/client.py
> +        models_list The list of accepted model names.
Maybe a `:` sign after parameters, like `models_list:`

2021-02-18 10:17 UTC, leikoilja commented on glocaltokens/const.py
> +]
Good call to move it into `const`

2021-02-18 10:21 UTC, ArnyminerZ commented
> To fully test it, we will probably need to patch `homegraph.home.devices` to return a list of objects like homegraph would actually return (just with a fake data). And then validate that we serialize and create `Device` objects correctly from that received payload.

Maybe creating a provider for fake Homegraph device data should do the trick? Just like we do with tokens.

2021-02-18 15:44 UTC, ArnyminerZ commented
Not sure why this isn't working on the json tests, but it does on the normal one. Will keep researching... Pushing here just for reference and progress updates.

2021-02-18 15:57 UTC, ArnyminerZ commented
Found out that for some reason when `get_google_devices_json` is called from `test_google_devices_json`, calls `self.get_google_devices` in some way that makes it return something like `<MagicMock name='get_google_devices()' id='140244469296240'>`, which isn't an array, what makes the loop not to run, and return an empty list.

2021-02-18 16:55 UTC, leikoilja commented
Lemme take a looook, @ArnyminerZ  👀 😄  Will push some change if/when i find something

2021-02-18 18:11 UTC, leikoilja commented
@ArnyminerZ, please see some of the changes I propose. It might not be the cleanest or the best way to do it, but maybe it can be a starting point?
![image](https://user-images.githubusercontent.com/10655107/108401860-1a8d0680-721d-11eb-9637-e09ced146c5b.png)

2021-02-18 21:17 UTC, ArnyminerZ reviewed
Awesome work! Everything seems right to me.

2021-02-18 21:22 UTC, ArnyminerZ commented
> 
> 
> @ArnyminerZ, please see some of the changes I propose. It might not be the cleanest or the best way to do it, but maybe it can be a starting point?

Yeah it's a bit dirty, but if for now it works, it's fine for me. In the future we may improve this.

2021-02-19 06:13 UTC, leikoilja approved these changes
I have a few questions regarding comments and cleaning up, but in general I agree with most of it! 💥  I'm going to approve, but please take a look on the comments if we can clean it up a bit before merging-in? 👍 
When you feel satisfied - merge it in 💥

2021-02-19 06:13 UTC, leikoilja commented on tests/factory/const.py
> +# Right now this is pretty useless, a great confusion. Don't delete just in case it's useful in the future.
Hm... this is a good find, might be useful sometime down the road. Shall we just move it to a separate branch, commit and leave it there for the time being?

2021-02-19 06:13 UTC, leikoilja commented on tests/factory/providers.py
> +)
Thanks for doing it, great idea!

2021-02-19 06:13 UTC, leikoilja commented on tests/factory/providers.py
> +    # TODO: This should be moved somewhere else
Do we need this comment this? Did you refer to the faker of `version`?

2021-02-19 06:13 UTC, leikoilja commented on tests/factory/providers.py
> +        return str(fake.pyint()) + "." + str(fake.pyint()) + "." + str(fake.pyint())
Can we not do it in a bit more pythonic way? 😄 Maybe like so:
`"{}.{}.{}".format(fake.pyint(), fake.pyint(), fake.pyint())`
or f-strings
`f"{fake.pyint()}{fake.pyint()}{fake.pyint()}"`

Although i live the `format` method more, seems more visual to me 😄

2021-02-19 06:13 UTC, leikoilja commented on tests/factory/providers.py
> +        """
We can just keep a shorted comment here like: "Using homegraph returned data as a reference" or smth similar

2021-02-19 06:13 UTC, leikoilja commented on tests/factory/providers.py
> +    #      ]
Do you think we still need it? And if so, what is the difference between homegraph_device and google_device?

2021-02-19 09:05 UTC, ArnyminerZ commented on tests/factory/providers.py
> +        """
Ok, that's fine, it was just to inform you about that.

2021-02-19 09:22 UTC, ArnyminerZ commented on tests/factory/providers.py
> +    # TODO: This should be moved somewhere else
Yes, I mean moving the version generator to a new provider since it's not properly related to Homegraph.

2021-02-19 09:25 UTC, ArnyminerZ commented on tests/factory/providers.py
> +    #      ]
`homegraph_device` is the model that is providen by the Google Documentation. I don't remember where did I get the `google_device` model from, but at the end, it's what we get from the RPC request. We might not need this, but it's the same as the content at `const.py`, it might be helpful, but not for now. As you've said, it may be appropiate to move it somewhere else.

2021-02-19 09:30 UTC, leikoilja approved these changes
Great stuff, thank you! 

Just a few minor comments and then feel free to merge

2021-02-19 09:30 UTC, leikoilja commented on tests/factory/providers.py
> +    # TODO: This should be moved somewhere else
If so, let's just create a custom Provider like `UtilsProvider` or smth, where we can move/add all similar generic stuff?

2021-02-19 09:30 UTC, leikoilja commented on tests/factory/providers.py
> +    #      ]
How about we move both to a separate branch `homegraph_mock` or smth like that on this repo?

2021-02-19 09:40 UTC, ArnyminerZ commented on tests/factory/providers.py
> +    # TODO: This should be moved somewhere else
Ok, sounds fair, done that

2021-02-19 09:41 UTC, ArnyminerZ commented
@leikoilja why is the `Labeler` failing? 🤔 Is that important?

2021-02-19 09:45 UTC, leikoilja commented
@ArnyminerZ, no no, that's not important yet. I will try fixing it today, not exactly sure why it doesn't have permissions to edit labels. It's a new github action that will help us automatically assign labels on PRs depending on what files were changes. For example, when `tests/*` changed it will assign `testing` label. See this config: [here](https://github.com/leikoilja/glocaltokens/blob/master/.github/labeler.yml)

2021-02-19 09:47 UTC, ArnyminerZ commented
Then I will merge once `3.9` test is complete. Even though it should pass without any issues.

2021-02-19 09:57 UTC, merged