Fixed #44
leikoilja/glocaltokens pull request #45
Opened 2021-03-13 09:37 UTC by ArnyminerZ

When initializing `Device`, `local_auth_token` won't get stored until all the checks are passed. This is used in `get_google_devices` for checking if the class has been initialized correctly, and if not, don't adding it to the devices list.

If the device is not added, a warning is shown to through the `LOGGER`.

*Note: Maybe a more detailed debug would be convenient*

2021-03-13 10:06 UTC, KapJI commented on glocaltokens/client.py
>          self.google_device = google_device
It's still set here, is it correct?

2021-03-13 10:06 UTC, KapJI commented on glocaltokens/client.py
>          self.google_device = google_device
It should be probably set to `None`.

2021-03-13 10:09 UTC, leikoilja requested changes
Thank you so much, @ArnyminerZ! 💥  You are the ⭐ !

Now that this patch is fixing a bug, we should really introduce a test for that, to ensure the same bug would never happen again.
There is a good methodology for bug solving: 
- if a bug occurs - find the bug
- write a test that should replicate the bug (the test must fail at this point)
- fix the bug in the code
- re-run the test (it must pass now) 

It would be amazing if you would have time to try knocking off the test for this one! If not, lemme know, i ll find some time to add it :)

2021-03-13 10:09 UTC, leikoilja commented on glocaltokens/client.py
>              return
Sorry for being a bit picky, Can we move all token related validation together, so `device_name` check is no in-between 😄

2021-03-13 10:09 UTC, leikoilja commented on glocaltokens/client.py
> +        self.local_auth_token = local_auth_token
Line 51 already does that assignment. Maybe we should start the `__init__` with:
`self.local_auth_token = None` as default and then do all the validation and if all the validations pass assign the token `self.local_auth_token = local_auth_token`? :)

2021-03-13 10:09 UTC, leikoilja commented on glocaltokens/client.py
> +                    LOGGER.warning("Device initialization failed, skipping.")
This is an explicit check, you would be just fine by saying 
`if device.local_auth_token` because as you have just made it - it will only be initialized if the token is passed and is valid. But it's totally up to you what style you prefer :)

2021-03-13 10:13 UTC, ArnyminerZ commented on glocaltokens/client.py
>          self.google_device = google_device
If doesn't matter, because it's checked that `self.ip` and `self.port` are valid IPs afterwards, so in case `google_device` is `None`, or `ip` or `port` are null, the function will be returning, and it will detect "an error".

See line 67

2021-03-13 10:18 UTC, ArnyminerZ commented
@leikoilja take a look at the tests, not sure if that was what you meant.

2021-03-13 10:21 UTC, ArnyminerZ commented on glocaltokens/client.py
> +        self.local_auth_token = local_auth_token
That was totally a typo. Fixed it

2021-03-13 10:22 UTC, KapJI commented on glocaltokens/client.py
>          self.google_device = google_device
Sorry, I meant that `self.local_auth_token` shouldn't be set twice and constructor should always set the same number of attributes. Github doesn't allow to add comment to line 51 here.

2021-03-13 10:22 UTC, ArnyminerZ commented on glocaltokens/client.py
> +                    LOGGER.warning("Device initialization failed, skipping.")
Yeah, I like more that. Quite cleaner.

2021-03-13 10:26 UTC, ArnyminerZ commented on glocaltokens/client.py
>              return
Not sure if this was what you meant, take a look

2021-03-13 10:29 UTC, ArnyminerZ commented
`test_get_google_devices` is now not initializing `google_devices` well, working on it

2021-03-13 12:29 UTC, ArnyminerZ commented
Not sure what's going wrong... @leikoilja @KapJI can you help me?

2021-03-13 13:04 UTC, KapJI commented on glocaltokens/client.py
> +                    devices.append(device)
Well, fake device in test is now filtered out here.

2021-03-13 13:21 UTC, leikoilja commented on glocaltokens/client.py
> +                    devices.append(device)
Indeed, you probably want the logic reversed:
`if not device.local_auth_token:`

2021-03-13 16:43 UTC, ArnyminerZ commented on glocaltokens/client.py
> +                    devices.append(device)
Totally my fault 🤦🏼 That's what tests are for 😅

2021-03-13 16:45 UTC, ArnyminerZ reviewed
Added changes

2021-03-13 18:42 UTC, leikoilja requested changes
Really nice! Thanks for a lot of very good changes! 
Thou, we are still missing one last test to make sure we test this part:
```python
                if not device.local_auth_token:
                    LOGGER.warning("Device initialization failed, skipping.")
                else:
                    devices.append(device)
```
To make sure if the token is invalid we don't return it in the list :)

2021-03-13 18:42 UTC, leikoilja commented on tests/test_client.py
>          # With no discover_devices, with no model_list
We would still need to add after this part one more clause something like (untested code):
```python
# With many devices returned from homegraph
# but one device having the invalid token
homegraph_device_valid = faker.homegraph_devices(count=1)[0]  # TODO: we probs need `faker.homegraph_device()` method
homegraph_device_invalid = faker.homegraph_devices(count=1)[0]
homegraph_device_invalid.local_auth_token = faker.word(). # setting invalid token intentionally
m_get_homegraph.return_value.home.devices = [homegraph_device_valid, homegraph_device_invalid]
google_devices = self.client.get_google_devices(disable_discovery=True)
self.assertEqual(len(homegraph_devices), 1)
self.assertEqual(homegraph_devices[0], homegraph_device_valid)
```

2021-03-13 18:42 UTC, leikoilja commented on glocaltokens/client.py
> +                if not device.local_auth_token:
Sorry, I know it's just me being picky, but i think this logic would make more sense if we reverse it:
```python
if device.local_auth_token:
  devices.append(device)   
else:                 
  LOGGER.warning("Device initialization failed, skipping.")
```
and the reason for that is that there might be more conditions when we need to ignore adding a device to a list, thou we shouldn't really care about them all at this point. All we want is "if device is valid - add it to a list, if not - just skip it" :) I hope i make sense

2021-03-13 20:51 UTC, ArnyminerZ commented on tests/test_client.py
>          # With no discover_devices, with no model_list
I've corrected it a little bit, but the last comparision cannot be done like this:
```python3
self.assertEqual(google_devices[0], homegraph_device_valid)
```
This is because `google_devices` contains `Device`s, and `homegraph_device_valid` is a `Struct`.
We can do this like:
```python3
# Get Homegraph from client
homegraph = self.client.get_homegraph()
homegraph_devices = homegraph.home.devices
self.assertEqual(homegraph_devices[0], homegraph_device_valid)
```
But it would be quite useless because we are overriding that `homegraph.home.devices` in:
```python3
m_get_homegraph.return_value.home.devices = [homegraph_device_valid, homegraph_device_invalid]
```

2021-03-13 20:55 UTC, ArnyminerZ commented on glocaltokens/client.py
> +                if not device.local_auth_token:
Yeah, totally makes sense, also it's easier to read, so modified it.

2021-03-15 09:27 UTC, leikoilja commented on tests/test_client.py
>          # With no discover_devices, with no model_list
ou, i see the issue, thanks for spotting it. 
Yeh, we can totally just compare the local tokens, but i propose we do an extra step and also validate the rest of properties of the device. We can even create a custom assertion for that. @ArnyminerZ, please see the last two commits that i have pushed here as a proposal of a custom assertion class that can help us `assertDevice`. What do u think about it?

2021-03-15 09:34 UTC, leikoilja approved these changes
Looks good to me 💯 
What do you think about it, @ArnyminerZ?

2021-03-15 10:23 UTC, ArnyminerZ commented
Looks great to me 💥 Merging

2021-03-15 10:23 UTC, merged