Added more debugging for bug-fixing
leikoilja/glocaltokens pull request #48
Opened 2021-03-21 21:06 UTC by ArnyminerZ

Maybe too redundant, but added everything just in case it is useful. Take a look at it.

Closes #47.

2021-03-21 21:26 UTC, DurgNomis-drol commented on glocaltokens/client.py
> +                    "Finding device in network? {}".format(not not network_devices)
`not not`?

2021-03-21 21:28 UTC, DurgNomis-drol approved these changes

2021-03-22 06:35 UTC, ArnyminerZ commented on glocaltokens/client.py
> +                    "Finding device in network? {}".format(not not network_devices)
Yeah, just a shitty way of saying "not None"

2021-03-22 06:47 UTC, KapJI requested changes

2021-03-22 06:47 UTC, KapJI commented on glocaltokens/utils/logs.py
> +def censure(text: str, replace: str = "*") -> str:
maybe `censor`?

2021-03-22 06:47 UTC, KapJI commented on glocaltokens/scanner.py
> +            )
@leikoilja is `model_list` still needed?

2021-03-22 06:47 UTC, KapJI commented on glocaltokens/client.py
> +                    "Finding device in network? {}".format(not not network_devices)
that's weird. Why not just `is not None`?

2021-03-22 06:47 UTC, KapJI commented on glocaltokens/scanner.py
> +        _LOGGER.debug("Setting self model to {}".format(model))
Can this be merged into single message?

2021-03-22 06:47 UTC, KapJI commented on glocaltokens/client.py
> +        LOGGER.debug(f"Setting self hardware to {hardware}")
Can this be merged?

2021-03-22 06:50 UTC, leikoilja commented on glocaltokens/client.py
> +        LOGGER.debug(f"Setting self hardware to {hardware}")
@KapJI is right, maybe we can log just once at the end somewhat like:
`Initialized new Google device instance with device_name={..}, local_auth_token={..} ....`

2021-03-22 07:07 UTC, leikoilja requested changes
Reeeally good work, @ArnyminerZ, thanks a lot! 💣 
We just need to clean it up a little and it's ready to be used!

Just a little question to both @ArnyminerZ and @KapJI, now this package checks global `DEBUG` variable flag and only if it's true it will show `logging.debug`. Is there any near way we can tag along the parent package/component logging level to use here? 
Maybe we can pass an extra optional parameter when we initialize client, somewhat like `verbose` that will set logging level to `debug`? So then on a parent package/integration (google_home in our example) we can pass `verbose` based if a user have `debug` flag set in HA `yaml` configuration for `google_home` component?

2021-03-22 07:07 UTC, leikoilja commented on glocaltokens/client.py
> +        LOGGER.debug("Invalidating access_token")
Can we move the log after the assignment, that way once we see the log entry we will be sure it's assigned `None` to variables? I know it should not break anywhere here either way, but it kind of makes sense to "do action first, log second"

2021-03-22 07:07 UTC, leikoilja commented on glocaltokens/scanner.py
> +            )
Good question, @KapJI.
We have dropped to maintain this list in `google-home`, do you think we still need it in `glocaltokens`, @ArnyminerZ?

2021-03-22 07:07 UTC, leikoilja commented on glocaltokens/utils/logs.py
> +    return replace * len(text)
Since we are using this util to print tokens and passwords, we really should add a test to make sure we censor correctly and are not printing any user sensitive data to the log without their consent

2021-03-22 07:17 UTC, KapJI commented
yeah, passing an extra flag sounds like a way to go. In HA component we can pass current verbosity level.

2021-03-22 10:04 UTC, ArnyminerZ commented on glocaltokens/scanner.py
> +            )
Well, I don't know, it might be useful for someone, maybe. If it doesn't bother, I wouldn't remove it, just in case.

2021-03-22 15:25 UTC, leikoilja commented on glocaltokens/client.py
> +                    "Finding device in network? {}".format(network_devices is not None)
Maybe
"Looking for a device in local network?"

2021-03-22 15:32 UTC, leikoilja requested changes
In general looks good to me. Please fix the failing tests and see some minor comments.

@KapJI do you want to take a look as well? :)

2021-03-22 15:32 UTC, leikoilja commented on glocaltokens/client.py
> +                    "Finding device in network? {}".format(network_devices is not None)
Maybe "Looking for a device in local network?"

2021-03-22 15:32 UTC, leikoilja commented on glocaltokens/client.py
> +                    LOGGER.debug("Appending device")
Let's be a bit more explicit here 
`LOGGER.debug(f"Appending {device.device_name} device to device list")`

2021-03-22 15:32 UTC, leikoilja commented on glocaltokens/client.py
> +                LOGGER.debug("local_auth_token is not initialized")
Let's be a bit more explicit here
`LOGGER.debug(f"local_auth_token is not initialized for {device.device_name}")`

2021-03-22 15:32 UTC, leikoilja commented on glocaltokens/scanner.py
> +            )
Let's make use of f-strings here as well instead of `format`, so we have it consistent everywhere :)

2021-03-22 15:32 UTC, leikoilja commented on glocaltokens/scanner.py
> +        return f"{{name:{self.name},ip:{self.ip},port:{self.port},model:{self.model}}}"
Is this actually working?

2021-03-22 15:32 UTC, leikoilja commented on glocaltokens/scanner.py
> +            )
Since we fallback to fetching all devices if no `model_list` is provided we can just keep it i guess :)

2021-03-22 15:32 UTC, leikoilja commented on tests/test_utils.py
> +class GLocalAuthenticationTokensClientTests(TestCase):
This is not a client test. Please name it something like `UtilsTests`

2021-03-22 15:32 UTC, leikoilja commented on tests/test_utils.py
> +        random = faker.word()
Shall we name it `secret_string` or smth?

2021-03-22 15:36 UTC, KapJI commented on glocaltokens/client.py
> +                    LOGGER.debug("Appending device")
Or `Adding {device.device_name} to devices list`.

2021-03-22 15:37 UTC, KapJI commented
Looks good to me overall

2021-03-23 17:09 UTC, ArnyminerZ commented on glocaltokens/scanner.py
> +        return f"{{name:{self.name},ip:{self.ip},port:{self.port},model:{self.model}}}"
Haven't tested, but it should, is there any visible issue? I've just added a test and it does

2021-03-23 17:10 UTC, ArnyminerZ commented on tests/test_utils.py
> +class GLocalAuthenticationTokensClientTests(TestCase):
Oops, just a copy-paste typo there.

2021-03-23 17:57 UTC, leikoilja requested changes
Looks great to me! 
@ArnyminerZ can you please fix failing tests that are broken now after you have added `censor` method? :) 

Also, do you mind us finding a way to pass the `verbose` parameter her to the `GLocalAuthenticationTokens` that will set the logger level to `debug`? I can do that tomorrow if you'd like :)

2021-03-24 18:20 UTC, leikoilja commented
@ArnyminerZ, @KapJI just pushed test fixes and `verbose` logging argument. Please take a look if you guys agree with it :)

2021-03-24 18:30 UTC, KapJI requested changes

2021-03-24 18:30 UTC, KapJI commented on glocaltokens/client.py
> +        verbose: Optional[bool] = False,
It's not `Optional`, just `bool`. `Optional` is `None` or `type`.

2021-03-24 18:30 UTC, KapJI commented on glocaltokens/utils/logs.py
>      replace: The character to instead of the content.
Update this.

2021-03-24 18:30 UTC, KapJI commented on glocaltokens/utils/logs.py
> +    text = text if text else ""
Why do you need this? `text` is specified as `str`, not `Optional[str]`.

2021-03-24 18:30 UTC, KapJI commented on glocaltokens/utils/logs.py
> +def censor(text: str, char: str = "*") -> str:
How about removing `char` argument completely? Why is it needed?

2021-03-24 18:30 UTC, KapJI commented on glocaltokens/utils/logs.py
> +    return censored_text
```python3
return text[0] + (len(text) - 1) * char if text else text
```

2021-03-24 18:48 UTC, leikoilja commented on glocaltokens/utils/logs.py
> +    text = text if text else ""
We have a problem here that it can we `None` when we call it from client passing in `master_token` for example

2021-03-24 18:49 UTC, leikoilja commented on glocaltokens/utils/logs.py
> +def censor(text: str, char: str = "*") -> str:
Good point, we don't really need it to be customizable :D

2021-03-24 18:49 UTC, leikoilja commented on glocaltokens/utils/logs.py
> +    return censored_text
haha you really don't like my "1. assignment; 2. return" :D will fix it thou ;)

2021-03-24 18:51 UTC, KapJI commented on glocaltokens/utils/logs.py
> +    text = text if text else ""
Then make text `Optional[str]` 🙂

2021-03-24 19:43 UTC, KapJI approved these changes
Thanks! 🚀

2021-03-24 20:36 UTC, merged