Setting up poetry
leikoilja/glocaltokens pull request #49
Opened 2021-03-24 19:22 UTC by leikoilja

- Setting up poetry
- Updating github actions to use poetry
- Updating contributions file
- Running pre-commit linters on all files

2021-03-24 19:46 UTC, KapJI commented
I'm not sure if `tox` is still useful with poetry. Testing with different python version can be done using Github Actions and I think it's better just to replace it `pytest`.

2021-03-24 19:54 UTC, KapJI commented on pyproject.toml
> +version = "0.0.0"
This should be an actual package version. Basically poetry should replace setuptools and `setup.py`.

2021-03-24 19:55 UTC, KapJI commented on pyproject.toml
> +version = "0.0.0"
This can be done in a separate PR to split this migration in parts.

2021-03-24 20:38 UTC, leikoilja commented on pyproject.toml
> +version = "0.0.0"
oh that's nice!

2021-03-24 20:45 UTC, leikoilja commented on pyproject.toml
> +version = "0.0.0"
@KapJI I have just tried `poetry build` locally and it works flawlessly, super nice!

2021-03-24 20:50 UTC, leikoilja commented
@KapJI, what you propose with `tox` sounds reasonable. But how would that look practically?
- Removing `tox` and `tox-gh-actions` from poetry
- Setting up github action to run tox independently from poetry?

2021-03-24 21:35 UTC, KapJI commented
I mean removing `tox` at all and run `pytest` directly from `poetry` 🙂

2021-03-24 21:39 UTC, KapJI commented on pyproject.toml
> +version = "0.0.0"
Then you should be also able to use `poetry publish` to release the new version.

2021-03-25 06:25 UTC, leikoilja commented on pyproject.toml
> +version = "0.0.0"
Exactly! Thanks for introducing `poetry`, such a time saver :P

2021-03-25 06:51 UTC, leikoilja commented
Roger that. FIxed it and i like it now :) 
What do you think, @KapJI?
As next PR we can enable mypy on this repo i guess :)

2021-03-25 07:53 UTC, KapJI requested changes
Few final touches to fully deprecate `setup.py`.

2021-03-25 07:53 UTC, KapJI commented on .github/workflows/tests.yaml
> +          poetry run pytest
Are're already running tests in linting job, this one can be removed.
You can rename linting to testing as well.

2021-03-25 07:53 UTC, KapJI commented on .pre-commit-config.yaml
>            - --quiet
Replace `black` and `isort` entries with ones which run versions installed by poetry. Similar to `ha-google-home`.

2021-03-25 07:53 UTC, KapJI commented on CONTRIBUTING.md
> +You can run the tests on all repository file with the command:
```suggestion
You can also run the tests on all repository files manually with the command:
```

2021-03-25 07:53 UTC, KapJI commented on pyproject.toml
> +"Bug Tracker" = "https://github.com/leikoilja/glocaltokens/issues"
Delete `HISTORY.md` and add link to release notes here.

2021-03-25 07:53 UTC, KapJI commented on pyproject.toml
> +repository = "https://github.com/leikoilja/glocaltokens"
Not sure if you need it but you can also add a `homepage` here.

2021-03-25 07:53 UTC, KapJI commented on pyproject.toml
> +readme = "README.md"
You can add `keywords` in this section to match old `setup.py`. Although I'm not sure how useful they are.

2021-03-25 07:53 UTC, KapJI commented on pyproject.toml
> +readme = "README.md"
Also it's worth adding `classifiers` here. See [poetry documentation](https://python-poetry.org/docs/pyproject/) and [packaging documentation](https://packaging.python.org/guides/distributing-packages-using-setuptools/#classifiers).

2021-03-25 08:17 UTC, KapJI commented on pyproject.toml
>  readme = "README.md"
Is it reordered by you or some tool? I think previous ordering was better with name and version on the top and links next to each other.

2021-03-25 08:18 UTC, KapJI approved these changes
Other than that, looks great!

2021-03-25 08:20 UTC, KapJI commented on tox.ini
>  [tox]
Missed that. `tox.ini` should be removed as tox is no longer used.

2021-03-25 08:22 UTC, leikoilja commented on pyproject.toml
>  readme = "README.md"
Just reordered it manually to be alphabetic :)

2021-03-25 08:24 UTC, KapJI commented on pyproject.toml
>  readme = "README.md"
I think this section is better to be semantically sorted 🙂

2021-03-25 08:24 UTC, leikoilja commented
Awesome, thanks, @KapJI for help! 💣 Let's merge it in! 💥

2021-03-25 08:24 UTC, merged