Enabling pylint
leikoilja/glocaltokens pull request #56
Opened 2021-04-05 06:34 UTC by leikoilja

Enabling pylint and linting

2021-04-05 09:17 UTC, KapJI requested changes
Add black compatible configuration in `pyproject.toml` (`[tool.pylint.format]`). You can copy it from `ha-google-home`.

2021-04-05 09:17 UTC, KapJI commented on .pre-commit-config.yaml
> +        exclude: ^glocaltokens/
Let's enable it for the whole project, but disable checks globally in `pyproject.toml` which are failing right now. This way `glocaltokens` will have at least some coverage.

2021-04-05 09:17 UTC, KapJI commented on tests/assertions.py
> +# pylint: disable=E1101
Please use human readable names.
```suggestion
# pylint: disable=no-member
```

2021-04-06 05:14 UTC, leikoilja commented on .pre-commit-config.yaml
> +        exclude: ^glocaltokens/
That reg-ex was meant to me `^glocaltokens/google/` to avoid checking proto files. I would really want to put `exclude` in the `pyproject.toml` file, but when i put it into `pyptoject.toml` it `exclude` doesn't work
```
[tool.pylint.format]
max-line-length = 88
exclude = "^glocaltokens/google/"
```

2021-04-06 06:05 UTC, KapJI commented on .pre-commit-config.yaml
> +        exclude: ^glocaltokens/
First of all it should be in [tools.pylint.master] section. Also options are called ignore (or ignore-patterns).

Try:

[tools.pylint.master]
ignore=google

2021-04-06 06:05 UTC, leikoilja commented on .pre-commit-config.yaml
> +        exclude: ^glocaltokens/
Having a wrong regex also well explains why i didn't need to change anything around the main logic in the client and scanner, that got me confused at first

2021-04-06 08:27 UTC, KapJI requested changes

2021-04-06 08:27 UTC, KapJI commented on glocaltokens/client.py
> +            if (ip_address and not port) or (not ip_address and port):
Let's cover all cases.
```suggestion
            if not ip_address or not port:
```

2021-04-06 08:27 UTC, KapJI commented on .pre-commit-config.yaml
> +        exclude: ^glocaltokens/google/
I still think it's better to move this to `pyproject.toml`. This way you can run `pylint` without `pre-commit`.

2021-04-06 08:27 UTC, KapJI commented on glocaltokens/client.py
> +        LOGGER.debug("Generated mac: %s", mac_string)
Btw, I found this code is generating incorrect mac address. It should be 12 chars long, not 14. And the way you geneate it is... creative.

2021-04-06 08:27 UTC, KapJI commented on glocaltokens/client.py
> +                # pylint: disable=no-else-return
Why not just dropping the `else`?

2021-04-06 08:27 UTC, KapJI commented on glocaltokens/scanner.py
> +# pylint: disable=arguments-differ
This sounds like a bug.

2021-04-06 08:27 UTC, KapJI commented on glocaltokens/scanner.py
> +# pylint: disable=too-few-public-methods
Disable it globally in `pyproject.toml`.

2021-04-06 08:27 UTC, KapJI commented on glocaltokens/scanner.py
> +# pylint: disable=too-many-locals
Move to `pyproject.toml`.

2021-04-06 08:27 UTC, KapJI commented on glocaltokens/scanner.py
> +# pylint: disable=unused-argument
Is it a public API? Can you just rename the argument?

2021-04-06 08:27 UTC, KapJI commented on glocaltokens/utils/network.py
> +    """Check if ip address is ipv4 type"""
```suggestion
    """Check if ip address is ipv4"""
```

2021-04-06 08:27 UTC, KapJI commented on glocaltokens/utils/network.py
> +    """Check if ip address is ipv6 type"""
```suggestion
    """Check if ip address is ipv6"""
```

2021-04-06 08:27 UTC, KapJI commented on tests/test_client.py
> +    # pylint: disable=too-many-arguments
Move to `pyproject.toml`.

2021-04-07 09:25 UTC, leikoilja commented on glocaltokens/client.py
> +            if (ip_address and not port) or (not ip_address and port):
Agree that the logic here can be improved, but let's keep it for another PR, cause it will also involve changing tests

2021-04-07 09:32 UTC, leikoilja commented on .pre-commit-config.yaml
> +        exclude: ^glocaltokens/google/
sorry i dont think i follow what you mean. 
If i add
```
[tools.pylint.master]
ignore = "google"
```
to `pyproject.toml` how to i run `pylint`? `poetry run pylint glocaltokens` still includes `google` directory and without `exclude` in `pre-commit-config` precommit `pylint` hook also fails on `google` dir

2021-04-07 09:33 UTC, leikoilja commented on glocaltokens/client.py
> +        LOGGER.debug("Generated mac: %s", mac_string)
hmmmm, we should look into that, maybe it would even be better to entirely switch to iOS mac which is uuid4 consistent format

2021-04-07 09:36 UTC, leikoilja commented on glocaltokens/scanner.py
> +# pylint: disable=arguments-differ
Well, not really, it's just overriding the listener method following the `pycast` example:
```
************* Module glocaltokens.scanner
glocaltokens/scanner.py:33:4: W0221: Parameters differ from overridden 'add_service' method (arguments-differ)
glocaltokens/scanner.py:38:4: W0221: Parameters differ from overridden 'update_service' method (arguments-differ)
glocaltokens/scanner.py:43:4: W0221: Parameters differ from overridden 'remove_service' method (arguments-differ)
```

2021-04-07 09:38 UTC, KapJI commented on glocaltokens/client.py
> +        LOGGER.debug("Generated mac: %s", mac_string)
How about just generating 6 random bytes?
```python
"".join([f"{random.randrange(256):02x}" for _ in range(6)])
```

2021-04-07 09:42 UTC, KapJI commented on glocaltokens/scanner.py
> +# pylint: disable=arguments-differ
Yes, and this is a potential bug if someone decide to use kwargs. You should use the same names for args:
https://github.com/jstasiak/python-zeroconf/blob/master/zeroconf/__init__.py#L1541

2021-04-07 09:50 UTC, KapJI commented on .pre-commit-config.yaml
> +        exclude: ^glocaltokens/google/
Ok, let's add an `exclude` here, I'll take a look how to do this in pylint config later.

2021-04-07 09:52 UTC, leikoilja commented on glocaltokens/client.py
> +        LOGGER.debug("Generated mac: %s", mac_string)
Sounds good, let's have a separate ticket for that

2021-04-07 10:04 UTC, KapJI approved these changes
Thanks! Let's move on with improving logging. That issue with redacting tokens from logs is pretty popular.

2021-04-07 10:45 UTC, merged

2021-04-07 10:45 UTC, leikoilja commented
Exactly, really wanna merge it quick so it's in a new release, @KapJI