Added access token expiration
leikoilja/glocaltokens pull request #9
Opened 2021-02-09 19:41 UTC by ArnyminerZ

Now, when an access token is generated, the generation date will be stored, and since its duration is of one hour, once that time is over, a new one will be generated. A bit of code reformatting has been done.

Also, some "security recommendations" have been added to the README.

2021-02-09 21:01 UTC, DurgNomis-drol approved these changes
Looks good to me.

This should also be applied to localAuthToken. It lives about 24 hours if i remember correctly.

2021-02-09 22:15 UTC, ArnyminerZ commented
Yeah, forgot it. Will add it ASAP

2021-02-09 22:23 UTC, ArnyminerZ commented
Added homegraph updates every 24h. Even though this is a kind of temporal fix. Error handling should be the option, I believe, but further testing must be done.

2021-02-10 11:56 UTC, leikoilja requested changes
That's really nice! Thanks for the PR!

Just a minor comment to make the code a bit more reusable/testable. Will be happy to merge right when it's fixed

2021-02-10 11:56 UTC, leikoilja commented on glocaltokens/client.py
> +                datetime.datetime.now().timestamp() - self.access_token_date.timestamp() > ACCESS_TOKEN_DURATION:
Would be nice to extract that `datetime` comparison into it's own method and reuse it

2021-02-10 12:02 UTC, ArnyminerZ commented on glocaltokens/client.py
> +                datetime.datetime.now().timestamp() - self.access_token_date.timestamp() > ACCESS_TOKEN_DURATION:
Makes sense, will work on it right now

2021-02-10 12:07 UTC, leikoilja commented on glocaltokens/client.py
> +                datetime.datetime.now().timestamp() - self.access_token_date.timestamp() > ACCESS_TOKEN_DURATION:
Thank you 💥

2021-02-10 12:08 UTC, ArnyminerZ commented on glocaltokens/client.py
> +                datetime.datetime.now().timestamp() - self.access_token_date.timestamp() > ACCESS_TOKEN_DURATION:
Added it 😉

2021-02-10 12:12 UTC, leikoilja approved these changes
Nice! Let's get it in

2021-02-10 12:13 UTC, merged